### ISSUE TITLE
Search a class name 

### ISSUE THREAD

**Issue by CoderWD** [wuba/WBBlades#1]
Hi  
I want to  search a class name location in file or belong to some class.

**Comment by pilaf-king** [comment]
OK ,We will solve

**Comment by pilaf-king** [comment]
这个可以这样解决，基于现有的开源代码，在遍历目标文件的时候打印类名即可。思考再三，这个功能暂时不放到开源代码里，因此issue 我先暂时关闭了哈，如果有什么问题可以QQ联系我们：395565391
