### ISSUE TITLE
源码询问

### ISSUE THREAD

**Issue by huzhongyin** [wuba/WBBlades#10]
您好，请问下，像struct class64,struct class64Info这些MACH-O的结构体我看您们是自己定义的，您们是如何知道这个结构体的结构的，有没有官方的相关文档说明，谢谢

**Comment by pilaf-king** [comment]
> 您好，请问下，像struct class64,struct class64Info这些MACH-O的结构体我看您们是自己定义的，您们是如何知道这个结构体的结构的，有没有官方的相关文档说明，谢谢

OC的结构比较成熟了，MachOView中就有。Swift的结构需要自己从源码中查找拼接：https://github.com/apple/swift/blob/d68d406dae39ea1677d586714b3991b8f2037dab/lib/IRGen/GenMeta.cpp

**Comment by pilaf-king** [comment]
> 您好，请问下，像struct class64,struct class64Info这些MACH-O的结构体我看您们是自己定义的，您们是如何知道这个结构体的结构的，有没有官方的相关文档说明，谢谢

Swift的结构在WBBlades的Swift5 分支已经列好了哈，部分结构后续还会更新，如下
struct SwiftClassTypeNoMethods {
    uint32_t Flag;
    uint32_t Parent;
    int32_t  Name;
    int32_t  AccessFunction;
    int32_t  FieldDescriptor;
    int32_t  SuperclassType;
    uint32_t MetadataNegativeSizeInWords;
    uint32_t MetadataPositiveSizeInWords;
    uint32_t NumImmediateMembers;
    uint32_t NumFields;
    uint32_t FieldOffsetVectorOffset;
};
