### ISSUE TITLE
运行检查无用类时Crash

### ISSUE THREAD

**Issue by tanysang** [wuba/WBBlades#12]
2021-05-31 10:03:13.070 WBBlades[24816:2796153] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[NSConcreteMutableData getBytes:range:]: range {2254311852, 150} exceeds data length 685746064'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff32e8fbe7 __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff6bcae5bf objc_exception_throw + 48
	2   Foundation                          0x00007fff354a605e -[NSData(NSData) getBytes:range:] + 616
	3   WBBlades                            0x0000000107b6e911 +[WBBladesTool readString:fixlen:fromFile:] + 321
	4   WBBlades                            0x0000000107b2073a +[WBBladesScanManager(UnuseClassScan) readSwiftTypes:set:fileData:] + 3098
	5   WBBlades                            0x0000000107b1bd6d +[WBBladesScanManager(UnuseClassScan) scanAllClassWithFileData:classes:] + 4205
	6   WBBlades                            0x0000000107b896c0 scanUnusedClass + 752
	7   WBBlades                            0x0000000107b88ef3 main + 387
	8   libdyld.dylib                       0x00007fff6ce55cc9 start + 1
	9   ???                                 0x0000000000000003 0x0 + 3
)
libc++abi.dylib: terminating with uncaught exception of type NSException
[1]    24816 abort       -unused

**Comment by pilaf-king** [comment]
> 2021-05-31 10:03:13.070 WBBlades[24816:2796153] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[NSConcreteMutableData getBytes:range:]: range {2254311852, 150} exceeds data length 685746064'
> *** First throw call stack:
> (
> 0 CoreFoundation 0x00007fff32e8fbe7 __exceptionPreprocess + 250
> 1 libobjc.A.dylib 0x00007fff6bcae5bf objc_exception_throw + 48
> 2 Foundation 0x00007fff354a605e -[NSData(NSData) getBytes:range:] + 616
> 3 WBBlades 0x0000000107b6e911 +[WBBladesTool readString:fixlen:fromFile:] + 321
> 4 WBBlades 0x0000000107b2073a +[WBBladesScanManager(UnuseClassScan) readSwiftTypes:set:fileData:] + 3098
> 5 WBBlades 0x0000000107b1bd6d +[WBBladesScanManager(UnuseClassScan) scanAllClassWithFileData:classes:] + 4205
> 6 WBBlades 0x0000000107b896c0 scanUnusedClass + 752
> 7 WBBlades 0x0000000107b88ef3 main + 387
> 8 libdyld.dylib 0x00007fff6ce55cc9 start + 1
> 9 ??? 0x0000000000000003 0x0 + 3
> )
> libc++abi.dylib: terminating with uncaught exception of type NSException
> [1] 24816 abort -unused

看起来是在读Swift的字符串时崩溃了，方便加个好友沟通下吗？😊    QQ:395565391
