### ISSUE TITLE
希望最终输出的结果，可以指定文件目录。

### ISSUE THREAD

**Issue by xiaoweiFive** [wuba/WBBlades#13]
> 假如目前有三个业务，我想指定输出music_file文件夹下的 无用类。

```

live_file
music_file
game_file

```

大佬们 能支持一下吗？

**Comment by springwinding** [comment]
不同文件夹下的文件已经被提取成统一的Mach-O文件结构， 没有了所属文件夹的信息， 所以不能针对文件夹进行输出。
