### ISSUE TITLE
.app 路径中间文件夹包含空格会报错

### ISSUE THREAD

**Issue by MyTimeforDevIos** [wuba/WBBlades#15]
```
~ blades -unused /Users/moonlight/Desktop/App\ 2021/Zeus
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
[1]    23624 segmentation fault  blades -unused /Users/moonlight/Desktop/App\ 2021/Zeus

```
另外向大佬问一个问题： `Swift无用代码检测依赖Debug包的符号表，检测到您的包里没有符号表，建议使用arm64真机的debug包扫描` 这里提到的真机 debug 包是指xcode在真机上run的包么？这种包应该怎么去获取

**Comment by pilaf-king** [comment]
> ```
> ~ blades -unused /Users/moonlight/Desktop/App\ 2021/Zeus
> usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
>        cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
> [1]    23624 segmentation fault  blades -unused /Users/moonlight/Desktop/App\ 2021/Zeus
> ```
> 
> 另外向大佬问一个问题： `Swift无用代码检测依赖Debug包的符号表，检测到您的包里没有符号表，建议使用arm64真机的debug包扫描` 这里提到的真机 debug 包是指xcode在真机上run的包么？这种包应该怎么去获取

是的，是指本地打出来的包。在Product这个文件夹下就可以找到

**Comment by MyTimeforDevIos** [comment]
找到了～，thanks
