### ISSUE TITLE
遍历section时，catlist section的name是__objc_catlist，匹配不到预定的__objc_nlcatlist__DATA，这是工具的bug？还是我自身工程的原因？

### ISSUE THREAD

**Issue by wuyy** [wuba/WBBlades#16]
<img width="1506" alt="WechatIMG257" src="https://user-images.githubusercontent.com/6121255/145186306-86bf5a32-97dd-4ced-a7df-f4bcd7053f37.png">

**Comment by pilaf-king** [comment]
> <img alt="WechatIMG257" width="1506" src="https://user-images.githubusercontent.com/6121255/145186306-86bf5a32-97dd-4ced-a7df-f4bcd7053f37.png">

感谢关注，方便加个QQ交流下吗，我QQ号是395565391
