### ISSUE TITLE
无符号崩溃解析的结果没有符号化

### ISSUE THREAD

**Issue by GCSNNB** [wuba/WBBlades#2]
我新建了一个工程，代码如下：

```
    NSArray *arr = @[@1, @2];
    [arr objectAtIndex:3];
```

Release模式下运行，崩溃。

然后在手机中导出ips文件，进行进行解析，解析文件没有符号化~

**Comment by pilaf-king** [comment]
我们加QQ详细了解下吧，因为这个已经使用过很多回了，解析不了可能是哪里没有对接好。我QQ是395565391

**Comment by pilaf-king** [comment]
> 我新建了一个工程，代码如下：
> 
> ```
>     NSArray *arr = @[@1, @2];
>     [arr objectAtIndex:3];
> ```
> 
> Release模式下运行，崩溃。
> 
> 然后在手机中导出ips文件，进行进行解析，解析文件没有符号化~

我们加QQ详细了解下吧，因为这个已经使用过很多回了，解析不了可能是哪里没有对接好。我QQ是395565391

**Comment by pilaf-king** [comment]
> 我们加QQ详细了解下吧，因为这个已经使用过很多回了，解析不了可能是哪里没有对接好。我QQ是395565391

issue我先关闭了哈，有问题的话我们QQ了解下
