### ISSUE TITLE
错误提示：‘在 Build Phases -> Link Binary with Libraries 中 加入 libswiftDemangle.tbd'

### ISSUE THREAD

**Issue by niuyongchang** [wuba/WBBlades#23]
环境：
- MacOS 11.3
- Xcode 13.0  

产生错误的方法是：
- ```+ [WBBladesTool getDemangleName:]```
- ```+ [WBBladesTool getDemangleNameWithCString:]```  

原因：
```libswiftDemangle.tbd```的symbols中，```"swift_demangle_getDemangledName"```变成了```"_swift_demangle_getDemangledName"```，引起了错误

**Comment by Simplegood** [comment]
您好，目前我们的libswiftDemangle.tbd的 symbols也是仅包含_swift_demangle_getDemangledName，通过swift_demangle_getDemangledName可以获取到方法。所以暂时无法模拟您描述的情况，您可以在本地尝试下通过_swift_demangle_getDemangledName来获取方法，如果可以我们尽快支持修复。
