### ISSUE TITLE
blades -unused xxx.app -from xxx.a xxx.a .... 

### ISSUE THREAD

**Issue by pengzhiqiang110** [wuba/WBBlades#24]
这个无用类检测,发现不是很准啊,检测出来的类很多都在使用呢,怎么就无用了呢

**Comment by songzhiming** [comment]
我也遇到了这个问题

**Comment by LuSheep** [comment]
> 我也遇到了这个问题

你好，请问你这边是OC类还是Swift类 被误检测为无用类的呢？

**Comment by LuSheep** [comment]
> @
> 
> > > 我也遇到了这个问题
> > 
> > 
> > 你好，请问你这边是OC类还是Swift类 被误检测为无用类的呢？
> 
> Swift

好的，感谢反馈，我们正在解决这个问题，争取近期完善，敬请期待

**Comment by LuSheep** [comment]
> @
> 
> > > 我也遇到了这个问题
> > 
> > 
> > 你好，请问你这边是OC类还是Swift类 被误检测为无用类的呢？
> 
> Swift

你好，可以再用咱们的可视化工具试一下哈，运行的时候target选择WBBladesCrashApp，如果还有问题欢迎随时反馈
