### ISSUE TITLE
Library not loaded: @rpath/libswiftDemangle.dylib

### ISSUE THREAD

**Issue by pengzishang** [wuba/WBBlades#26]
当我进行安装后
$ git clone https://github.com/wuba/WBBlades.git
$ cd WBBlades
$ sudo make install

准备检测代码
我输入
blades -unused /Users/deshglh/Library/Developer/Xcode/DerivedData/GuruClub-dnlcblbkuusqhdamckjrtkqowzle/Build/Products/Debug-iphoneos/GuruClub.app

提示dyld[67938]: Library not loaded: @rpath/libswiftDemangle.dylib
  Referenced from: /usr/local/bin/blades
  Reason: tried: '/usr/local/bin/../lib/libswiftDemangle.dylib' (no such file), '/usr/local/bin/../lib/libswiftDemangle.dylib' (no such file), '/usr/local/lib/libswiftDemangle.dylib' (no such file), '/usr/lib/libswiftDemangle.dylib' (no such file)
[1]    67938 abort      blades -unused  -from

是我哪里没操作对?

**Comment by pilaf-king** [comment]
看起来是环境问题，方便加个好友沟通下吗？😊 QQ:395565391
