### ISSUE TITLE
[1]    96318 segmentation fault  blades -unused Test.app

### ISSUE THREAD

**Issue by niuyongchang** [wuba/WBBlades#27]
在创建DemoApp测试时是可以正常检测并输出的，但是用在正式App上就总是报这个错误，没有其它更多的提示信息了。而且每次错误，前面的'96318'这个序号还都不一样，大佬们能否查一查这可能是什么原因，感谢

**Comment by LuSheep** [comment]
> 在创建DemoApp测试时是可以正常检测并输出的，但是用在正式App上就总是报这个错误，没有其它更多的提示信息了。而且每次错误，前面的'96318'这个序号还都不一样，大佬们能否查一查这可能是什么原因，感谢

你好，请问这个正式包是从项目Products文件夹下取到的包吗，并且是真机arm64架构的

**Comment by niuyongchang** [comment]
> > 在创建DemoApp测试时是可以正常检测并输出的，但是用在正式App上就总是报这个错误，没有其它更多的提示信息了。而且每次错误，前面的'96318'这个序号还都不一样，大佬们能否查一查这可能是什么原因，感谢
> 
> 你好，请问这个正式包是从项目Products文件夹下取到的包吗，并且是真机arm64架构的

是的，真机，arm64 debug包

**Comment by LuSheep** [comment]
> 

你好，方便把二进制文件发过来我这边调试一下吗，方便的话可以加下Q或直接邮箱：402707492

**Comment by CodeKevin** [comment]
+1
