### ISSUE TITLE
When I use the unused script, I hope the result can exclude the PodsDummy_xxxx

### ISSUE THREAD

**Issue by JustLee-me** [wuba/WBBlades#29]
"PodsDummy_FirebaseCoreDiagnostics",
    "PodsDummy_FirebaseCoreDiagnostics",
    "PodsDummy_FirebaseInstallations",
    "PodsDummy_FirebaseAnalytics",

**Comment by LuSheep** [comment]
收到您的建议，我们将会在最近推出的GUI工具中进行优化~

**Comment by LuSheep** [comment]
we had already optimized this problem, you can pull the latest project to experience, thx.
