### ISSUE TITLE
pod install 出错

### ISSUE THREAD

**Issue by ZuhanLin** [wuba/WBBlades#33]
请问pod要求的最低版本是多少？

**Comment by springwinding** [comment]
我本地是1.11.3， 你的版本号是多少？ 我修复一下这个问题。

**Comment by ZuhanLin** [comment]
![image](https://user-images.githubusercontent.com/5183529/177077070-9bb28624-6756-4570-acd3-1e4fcec865e7.png)

**Comment by springwinding** [comment]
我把本地环境切换到1.9.3也没报错， 建议升级一下cocospod版本在试下：
   sudo gem uninstall -n /usr/local/bin cocoapods
    // 安装最新版本，输入
    sudo gem install -n /usr/local/bin cocoapods
    // 或者指定版本号安装
    sudo gem install -n /usr/local/bin cocoapods -v 1.11.3

**Comment by canhth** [comment]
I'm getting `pod install` error on M1 Max - Monterey. 

- Cocoapods 1.11.3
- Tried these solutions but not work at all: 
+ https://github.com/ffi/ffi/issues/814#issuecomment-664824997
+ https://github.com/CocoaPods/CocoaPods/issues/9890#issuecomment-855582254 

<img width="780" alt="Screen Shot 2022-07-26 at 13 19 21" src="https://user-images.githubusercontent.com/7752679/180937039-49fd7ddc-b032-4987-9e7d-ef3a2d8c9e50.png">

**Comment by springwinding** [comment]
sudo gem install ffi
重新安装一下ffi试试呢？

**Comment by canhth** [comment]
```
sudo gem uninstall cocoapods
sudo gem install ffi -- --enable-system-libffi
brew install cocoapods 
```

This one just works for me :)

**Comment by springwinding** [comment]
Thanks for your questions,   have a nice use of the tool.

**Comment by springwinding** [comment]
Thanks for your questions, have a nice use of the tool.
