### ISSUE TITLE
直把我的项目删了 干！！！！！！

### ISSUE THREAD

**Issue by Miles-Matheson** [wuba/WBBlades#38]
直把我的项目删了 干！！！！！！

**Comment by springwinding** [comment]
什么场景删除了， 是用的哪个功能呢？ 我排查一下具体原因

**Comment by Miles-Matheson** [comment]
我拖拽ipa包到项目内 检测为使用类 然后点击检测 你的项目就报错崩溃 然后我的直接整个项目没了    我十几天没同步了 这一下子。。。。感觉天塌了，。。。。 还能找回吗

**Comment by LuSheep** [comment]
> 

你好，方便加个微信吗，我们看一下

**Comment by springwinding** [comment]
你好，+个微信呗： springwinding
















在 2022-10-14 14:42:09，"Miles" ***@***.***> 写道：

直把我的项目删了 干！！！！！！

**Comment by erduoniba** [comment]
项目应该有git管理吧？

**Comment by springwinding** [comment]
如果ipa路径为：项目路径+空格+名称.ipa,  移除工具生成的中间文件时因存在空格， 会变成 rm -rf 项目路径， 目前已紧急修复此问题，请更新到最新版工具，以免在使用过程中造成误删除影响，给您带来的不便深感歉意。
