### ISSUE TITLE
请问下，目前对swift包支持不够么？

### ISSUE THREAD

**Issue by dyljqq** [wuba/WBBlades#42]
我导入纯swift包，会有crash。

2022-11-17 15:47:55.226624+0800 WBBladesCrashApp[69393:17883431] [General] (
	0   CoreFoundation                      0x000000018b39d1a8 __exceptionPreprocess + 240
	1   libobjc.A.dylib                     0x000000018b0e7e04 objc_exception_throw + 60
	2   Foundation                          0x000000018c1fbad4 -[NSData(NSData) getBytes:length:] + 0
	3   WBBladesCrashApp                    0x0000000104388314 +[WBBladesTool readString:fixlen:fromFile:] + 260
	4   WBBladesCrashApp                    0x0000000104383128 +[WBBladesScanManager(UnuseClassScan) readSwiftTypes:set:fileData:] + 6792
	5   WBBladesCrashApp                    0x000000010437e7c4 +[WBBladesScanManager(UnuseClassScan) scanAllClassWithFileData:classes:progressBlock:] + 2968
	6   WBBladesCrashApp                    0x000000010435f9ec +[WBBladesInterface scanUnusedClassWithAppPath:fromLibs:] + 920
	7   WBBladesCrashApp                    0x000000010427a054 $s16WBBladesCrashApp36BladesUnusedClassCheckViewControllerC09beginScaneF0yyypFyycfU_ + 376
	8   WBBladesCrashApp                    0x000000010424b900 $sIeg_IeyB_TR + 48
	9   libdispatch.dylib                   0x0000000104b9c804 _dispatch_call_block_and_release + 32
	10  libdispatch.dylib                   0x0000000104b9e3a8 _dispatch_client_callout + 20
	11  libdispatch.dylib                   0x0000000104ba1398 _dispatch_queue_override_invoke + 1188
	12  libdispatch.dylib                   0x0000000104bb5fc8 _dispatch_root_queue_drain + 408
	13  libdispatch.dylib                   0x0000000104bb6bdc _dispatch_worker_thread2 + 196
	14  libsystem_pthread.dylib             0x000000010469ff48 _pthread_wqthread + 228
	15  libsystem_pthread.dylib             0x00000001046a7a9c start_wqthread + 8
)

// 这个方法中的 [fileData getBytes:buffer range:range];
+ (NSString *)readString:(NSRange &)range fixlen:(NSUInteger)len fromFile:(NSData *)fileData {
    range = NSMakeRange(NSMaxRange(range), len);
    uint8_t *buffer = (uint8_t *)malloc(len + 1); buffer[len] = '\0';
    [fileData getBytes:buffer range:range];
    NSString *str = NSSTRING(buffer);
    free (buffer);
    return [self replaceEscapeCharsInString:str];
}

Thread 12: "*** -[NSConcreteMutableData getBytes:range:]: range {419430429, 150} exceeds data length 11429520"

**Comment by springwinding** [comment]
你好, 方便+个微信么，我们排查一下 springwinding

**Comment by dyljqq** [comment]
您好，已加。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: springwinding ***@***.***&gt;
发送时间: 2022年11月17日 18:49
收件人: wuba/WBBlades ***@***.***&gt;
抄送: 东方宜玲 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [wuba/WBBlades] 请问下，目前对swift包支持不够么？ (Issue #42)





 
你好, 方便+个微信么，我们排查一下 springwinding

**Comment by springwinding** [comment]
你好，感谢反馈。 检测崩溃问题已修复， 近期我们将更新新版本，敬请期待。
