### ISSUE TITLE
OC和swift的混编项目是不是支持的不太好啊

### ISSUE THREAD

**Issue by jiangchao0829** [wuba/WBBlades#43]
OC和swift的混编项目是不是支持的不太好啊
扫描出4000多个无用类，我挑了几个都是swift的 都有在用。。。。

**Comment by springwinding** [comment]
你好，感谢反馈，针对混编检测Swift无用类的问题已修复， 近期我们将更新新版本，敬请期待。

**Comment by jiangchao0829** [comment]
新版本执行就崩溃啊
<img width="1246" alt="image" src="https://user-images.githubusercontent.com/117245393/207797994-d6e8a51b-e66e-4059-9d00-19965c062672.png">

**Comment by springwinding** [comment]
你好已修复， 辛苦在更新下。 如有问题加微信springwinding，一起看下。

**Comment by mumuWorld** [comment]
新版本，同样报错。。。

**Comment by zengql512** [comment]
> 新版本，同样报错。。。

能贴下报错信息吗？

**Comment by zengql512** [comment]
> 新版本，同样报错。。。

也可加下微信zqlong320，便于进一步沟通问题。

**Comment by dadadong** [comment]
> 新版本执行就崩溃啊 <img alt="image" width="1246" src="https://user-images.githubusercontent.com/117245393/207797994-d6e8a51b-e66e-4059-9d00-19965c062672.png">

@springwinding 刚拉最新的master代码，这个二进制的越界崩溃还在的，我临时添加越界判断先能使用了，望早修复
