### ISSUE TITLE
EXC_BAD_ACCESS Crash

### ISSUE THREAD

**Issue by mumuWorld** [wuba/WBBlades#45]
无用类检测的时候 直接就crash 了
![image](https://user-images.githubusercontent.com/19208505/208398061-95072e32-b35c-4cc0-9ad3-c136f104ac2b.png)
<img width="1126" alt="image" src="https://user-images.githubusercontent.com/19208505/208401951-e5e2b5d5-99af-4c87-812d-b78a7aa7edf7.png">

Translated Report (Full Report Below)
-------------------------------------

Process:               WBBladesCrashApp [8988]
Path:                  /Users/USER/Library/Developer/Xcode/DerivedData/WBBlades-auardhnotmoowpecyskwsgogtjcg/Build/Products/Debug/WBBladesCrashApp.app/Contents/MacOS/WBBladesCrashApp
Identifier:            com.jiangyan.app.WBBlades
Version:               1.0 (1)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               508161570

Date/Time:             2022-12-19 17:47:24.6065 +0800
OS Version:            macOS 13.0.1 (22A400)
Report Version:        12
Anonymous UUID:        DB5C61DF-C8DD-8F24-243B-05A3D52C7091

Sleep/Wake UUID:       07576904-E6D4-4E5F-84BE-924BD0943C0B

Time Awake Since Boot: 360000 seconds
Time Since Wake:       27607 seconds

System Integrity Protection: enabled

Crashed Thread:        2  Dispatch queue: com.apple.root.default-qos

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x00000004cb207c80
Exception Codes:       0x0000000000000001, 0x00000004cb207c80

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [8988]

VM Region Info: 0x4cb207c80 is not in any region.  Bytes after previous region: 2522241  Bytes before following region: 47057961856
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      MALLOC_LARGE                4c8b64000-4cafa0000    [ 36.2M] rw-/rwx SM=PRV  
--->  GAP OF 0xaf5060000 BYTES
      commpage (reserved)         fc0000000-1000000000   [  1.0G] ---/--- SM=NUL  ...(unallocated)

Kernel Triage:
VM - pmap_enter retried due to resource shortage
VM - pmap_enter retried due to resource shortage
VM - pmap_enter retried due to resource shortage
VM - pmap_enter retried due to resource shortage
VM - pmap_enter retried due to resource shortage

Thread 0::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	       0x1b27dadf0 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x1b27ec8d8 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x1b27e3638 mach_msg_overwrite + 540
3   libsystem_kernel.dylib        	       0x1b27db16c mach_msg + 24
4   CoreFoundation                	       0x1b28f9bdc __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x1b28f84c8 __CFRunLoopRun + 1232
6   CoreFoundation                	       0x1b28f78a4 CFRunLoopRunSpecific + 612
7   HIToolbox                     	       0x1bbf6b3bc RunCurrentEventLoopInMode + 292
8   HIToolbox                     	       0x1bbf6b200 ReceiveNextEventCommon + 672
9   HIToolbox                     	       0x1bbf6af48 _BlockUntilNextEventMatchingListInModeWithFilter + 72
10  AppKit                        	       0x1b5b50630 _DPSNextEvent + 632
11  AppKit                        	       0x1b5b4f7c0 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 728
12  AppKit                        	       0x1b5b43bf0 -[NSApplication run] + 464
13  AppKit                        	       0x1b5b1b058 NSApplicationMain + 880
14  WBBladesCrashApp              	       0x1009c2518 static NSApplicationDelegate.main() + 40
15  WBBladesCrashApp              	       0x1009c24e0 static AppDelegate.$main() + 44 (AppDelegate.swift:10)
16  WBBladesCrashApp              	       0x1009c2580 main + 28
17  dyld                          	       0x1b24efe50 start + 2544

Thread 1:
0   libsystem_pthread.dylib       	       0x1b2814e18 start_wqthread + 0

Thread 2 Crashed::  Dispatch queue: com.apple.root.default-qos
0   libsystem_platform.dylib      	       0x1b28453dc _platform_strcmp + 12
1   WBBladesCrashApp              	       0x100a91008 +[WBBladesScanManager(UnuseClassScan) scanSELCallerWithAddress:heigh:low:begin:end:] + 304 (WBBladesScanManager+UnuseClassScan.mm:271)
2   WBBladesCrashApp              	       0x100a9749c +[WBBladesScanManager(UnuseClassScan) findCallAccessFunc:accessFunc:fileData:] + 1508 (WBBladesScanManager+UnuseClassScan.mm:1104)
3   WBBladesCrashApp              	       0x100a96bf8 +[WBBladesScanManager(UnuseClassScan) readSwiftTypes:set:fileData:] + 14760 (WBBladesScanManager+UnuseClassScan.mm:1050)
4   WBBladesCrashApp              	       0x100a90540 +[WBBladesScanManager(UnuseClassScan) scanAllClassWithFileData:classes:progressBlock:] + 2592 (WBBladesScanManager+UnuseClassScan.mm:195)
5   WBBladesCrashApp              	       0x100a7f0e0 +[WBBladesInterface scanUnusedClassWithAppPath:fromLibs:] + 920 (WBBladesInterface.m:292)
6   WBBladesCrashApp              	       0x1009b9234 closure #1 in BladesUnusedClassCheckViewController.beginScanUnusedClass(_:) + 376 (BladesUnusedClassCheckViewController.swift:78)
7   WBBladesCrashApp              	       0x100990198 thunk for @escaping @callee_guaranteed () -> () + 48
8   libdispatch.dylib             	       0x1b26919dc _dispatch_call_block_and_release + 32
9   libdispatch.dylib             	       0x1b2693504 _dispatch_client_callout + 20
10  libdispatch.dylib             	       0x1b26965f0 _dispatch_queue_override_invoke + 788
11  libdispatch.dylib             	       0x1b26a4f94 _dispatch_root_queue_drain + 396
12  libdispatch.dylib             	       0x1b26a57c0 _dispatch_worker_thread2 + 164
13  libsystem_pthread.dylib       	       0x1b28160c4 _pthread_wqthread + 228
14  libsystem_pthread.dylib       	       0x1b2814e20 start_wqthread + 8

**Comment by zengql512** [comment]
感谢对WBBlades的支持，此问题已在新版中修复，请更新试试，谢谢！

**Comment by zengql512** [comment]
感谢对WBBlades的支持，此问题已在新版中修复，请更新试试，谢谢！

**Comment by mumuWorld** [comment]
可是我用的就是新版啊？

**Comment by mumuWorld** [comment]
e .我没用master我的问题，
