### ISSUE TITLE
字典key为nil  [__NSDictionaryM setObject:forKeyedSubscript:]: key cannot be nil

### ISSUE THREAD

**Issue by mumuWorld** [wuba/WBBlades#46]
![image](https://user-images.githubusercontent.com/19208505/208637807-2d2c69c0-48a4-47fe-87ee-0bfd378942ca.png)

2022-12-20 17:48:51.994663+0800 WBBladesCrashApp[5947:65559] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSDictionaryM setObject:forKeyedSubscript:]: key cannot be nil'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001880b4418 __exceptionPreprocess + 176
	1   libobjc.A.dylib                     0x0000000187bfeea8 objc_exception_throw + 60
	2   CoreFoundation                      0x0000000188199cc4 -[__NSCFString characterAtIndex:].cold.1 + 0
	3   CoreFoundation                      0x00000001881a6e4c -[__NSDictionaryM setObject:forKeyedSubscript:].cold.2 + 0
	4   CoreFoundation                      0x0000000188001a0c -[__NSDictionaryM setObject:forKeyedSubscript:] + 928
	5   WBBladesCrashApp                    0x00000001022e6324 +[WBBladesScanManager(UnuseClassScan) readClassList:aimClasses:set:fileData:classSize:] + 2892
	6   WBBladesCrashApp                    0x00000001022e2a3c +[WBBladesScanManager(UnuseClassScan) scanAllClassWithFileData:classes:progressBlock:] + 3392
	7   WBBladesCrashApp                    0x00000001022c3b48 +[WBBladesInterface scanUnusedClassWithAppPath:fromLibs:] + 920
	8   WBBladesCrashApp                    0x0000000102173c88 $s16WBBladesCrashApp36BladesUnusedClassCheckViewControllerC09beginScaneF0yyypFyycfU_ + 372
	9   WBBladesCrashApp                    0x0000000102141e54 $sIeg_IeyB_TR + 48
	10  libdispatch.dylib                   0x0000000102a68ecc _dispatch_call_block_and_release + 32
	11  libdispatch.dylib                   0x0000000102a6a9d4 _dispatch_client_callout + 20
	12  libdispatch.dylib                   0x0000000102a6d9a0 _dispatch_queue_override_invoke + 1196
	13  libdispatch.dylib                   0x0000000102a8293c _dispatch_root_queue_drain + 408
	14  libdispatch.dylib                   0x0000000102a83560 _dispatch_worker_thread2 + 196
	15  libsystem_pthread.dylib             0x0000000102677cec _pthread_wqthread + 228
	16  libsystem_pthread.dylib             0x000000010267fa7c start_wqthread + 8
)

**Comment by zengql512** [comment]
> ![image](https://user-images.githubusercontent.com/19208505/208637807-2d2c69c0-48a4-47fe-87ee-0bfd378942ca.png)
> 
> 2022-12-20 17:48:51.994663+0800 WBBladesCrashApp[5947:65559] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSDictionaryM setObject:forKeyedSubscript:]: key cannot be nil' *** First throw call stack: ( 0 CoreFoundation 0x00000001880b4418 __exceptionPreprocess + 176 1 libobjc.A.dylib 0x0000000187bfeea8 objc_exception_throw + 60 2 CoreFoundation 0x0000000188199cc4 -[__NSCFString characterAtIndex:].cold.1 + 0 3 CoreFoundation 0x00000001881a6e4c -[__NSDictionaryM setObject:forKeyedSubscript:].cold.2 + 0 4 CoreFoundation 0x0000000188001a0c -[__NSDictionaryM setObject:forKeyedSubscript:] + 928 5 WBBladesCrashApp 0x00000001022e6324 +[WBBladesScanManager(UnuseClassScan) readClassList:aimClasses:set:fileData:classSize:] + 2892 6 WBBladesCrashApp 0x00000001022e2a3c +[WBBladesScanManager(UnuseClassScan) scanAllClassWithFileData:classes:progressBlock:] + 3392 7 WBBladesCrashApp 0x00000001022c3b48 +[WBBladesInterface scanUnusedClassWithAppPath:fromLibs:] + 920 8 WBBladesCrashApp 0x0000000102173c88 $s16WBBladesCrashApp36BladesUnusedClassCheckViewControllerC09beginScaneF0yyypFyycfU_ + 372 9 WBBladesCrashApp 0x0000000102141e54 $sIeg_IeyB_TR + 48 10 libdispatch.dylib 0x0000000102a68ecc _dispatch_call_block_and_release + 32 11 libdispatch.dylib 0x0000000102a6a9d4 _dispatch_client_callout + 20 12 libdispatch.dylib 0x0000000102a6d9a0 _dispatch_queue_override_invoke + 1196 13 libdispatch.dylib 0x0000000102a8293c _dispatch_root_queue_drain + 408 14 libdispatch.dylib 0x0000000102a83560 _dispatch_worker_thread2 + 196 15 libsystem_pthread.dylib 0x0000000102677cec _pthread_wqthread + 228 16 libsystem_pthread.dylib 0x000000010267fa7c start_wqthread + 8 )

感谢支持WBBlades，已修复该问题，欢迎使用！
