### ISSUE TITLE
检查无用类是崩溃

### ISSUE THREAD

**Issue by luluaidota** [wuba/WBBlades#49]
-[NSConcreteMutableData getBytes:range:]: range {18446744068510046853, 8} exceeds data length 86567552'

**Comment by springwinding** [comment]
你好， 辛苦贴下崩溃堆栈，我们定位一下崩溃原因。

**Comment by luluaidota** [comment]
2023-02-23 16:18:56.779385+0800 WBBladesCrashApp[32134:217689] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[NSConcreteMutableData getBytes:range:]: range {18446744069315353205, 8} exceeds data length 86565296'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007ff8108cd3eb __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007ff810419e25 objc_exception_throw + 48
	2   Foundation                          0x00007ff8116ab58d -[NSData(NSData) getBytes:length:] + 0
	3   WBBladesCrashApp                    0x0000000104e86453 +[WBBladesTool readBytes:length:fromFile:] + 291
	4   WBBladesCrashApp                    0x0000000104e8ba98 +[WBBladesTool getSwiftTypeNameWithSwiftType:Offset:vm:fileData:] + 2568
	5   WBBladesCrashApp                    0x0000000104e8bb82 +[WBBladesTool getSwiftTypeNameWithSwiftType:Offset:vm:fileData:] + 2802
	6   WBBladesCrashApp                    0x0000000104e83a10 +[WBBladesScanManager(UnuseClassScan) statSwiftClassSize:andSwift5Types:fileData:] + 1584
	7   WBBladesCrashApp                    0x0000000104e743fc +[WBBladesScanManager(UnuseClassScan) diffClasses:used:classSize:fileData:] + 1468
	8   WBBladesCrashApp                    0x0000000104e73cea +[WBBladesScanManager(UnuseClassScan) scanAllClassWithFileData:classes:progressBlock:] + 5610
	9   WBBladesCrashApp                    0x0000000104e4a744 +[WBBladesInterface scanUnusedClassWithAppPath:fromLibs:] + 1140
	10  WBBladesCrashApp                    0x0000000104cd9f9e $s16WBBladesCrashApp36BladesUnusedClassCheckViewControllerC09beginScaneF0yyypFyycfU_ + 382
	11  WBBladesCrashApp                    0x0000000104ca5c28 $sIeg_IeyB_TR + 40
	12  libdispatch.dylib                   0x00000001055d3e94 _dispatch_call_block_and_release + 12
	13  libdispatch.dylib                   0x00000001055d512c _dispatch_client_callout + 8
	14  libdispatch.dylib                   0x00000001055d786b _dispatch_queue_override_invoke + 1078
	15  libdispatch.dylib                   0x00000001055e9d1b _dispatch_root_queue_drain + 347
	16  libdispatch.dylib                   0x00000001055ea821 _dispatch_worker_thread2 + 205
	17  libsystem_pthread.dylib             0x000000010520441d _pthread_wqthread + 256
	18  libsystem_pthread.dylib             0x000000010520abe7 start_wqthread + 15
)
2023-02-23 16:18:56.787859+0800 WBBladesCrashApp[32134:217689] [General] An uncaught exception was raised
2023-02-23 16:18:56.787938+0800 WBBladesCrashApp[32134:217689] [General] *** -[NSConcreteMutableData getBytes:range:]: range {18446744069315353205, 8} exceeds data length 86565296
2023-02-23 16:18:56.788057+0800 WBBladesCrashApp[32134:217689] [General] (
	0   CoreFoundation                      0x00007ff8108cd3eb __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007ff810419e25 objc_exception_throw + 48
	2   Foundation                          0x00007ff8116ab58d -[NSData(NSData) getBytes:length:] + 0
	3   WBBladesCrashApp                    0x0000000104e86453 +[WBBladesTool readBytes:length:fromFile:] + 291
	4   WBBladesCrashApp                    0x0000000104e8ba98 +[WBBladesTool getSwiftTypeNameWithSwiftType:Offset:vm:fileData:] + 2568
	5   WBBladesCrashApp                    0x0000000104e8bb82 +[WBBladesTool getSwiftTypeNameWithSwiftType:Offset:vm:fileData:] + 2802
	6   WBBladesCrashApp                    0x0000000104e83a10 +[WBBladesScanManager(UnuseClassScan) statSwiftClassSize:andSwift5Types:fileData:] + 1584
	7   WBBladesCrashApp                    0x0000000104e743fc +[WBBladesScanManager(UnuseClassScan) diffClasses:used:classSize:fileData:] + 1468
	8   WBBladesCrashApp                    0x0000000104e73cea +[WBBladesScanManager(UnuseClassScan) scanAllClassWithFileData:classes:progressBlock:] + 5610
	9   WBBladesCrashApp                    0x0000000104e4a744 +[WBBladesInterface scanUnusedClassWithAppPath:fromLibs:] + 1140
	10  WBBladesCrashApp                    0x0000000104cd9f9e $s16WBBladesCrashApp36BladesUnusedClassCheckViewControllerC09beginScaneF0yyypFyycfU_ + 382
	11  WBBladesCrashApp                    0x0000000104ca5c28 $sIeg_IeyB_TR + 40
	12  libdispatch.dylib                   0x00000001055d3e94 _dispatch_call_block_and_release + 12
	13  libdispatch.dylib                   0x00000001055d512c _dispatch_client_callout + 8
	14  libdispatch.dylib                   0x00000001055d786b _dispatch_queue_override_invoke + 1078
	15  libdispatch.dylib                   0x00000001055e9d1b _dispatch_root_queue_drain + 347
	16  libdispatch.dylib                   0x00000001055ea821 _dispatch_worker_thread2 + 205
	17  libsystem_pthread.dylib             0x000000010520441d _pthread_wqthread + 256
	18  libsystem_pthread.dylib             0x000000010520abe7 start_wqthread + 15
)
libc++abi: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[NSConcreteMutableData getBytes:range:]: range {18446744069315353205, 8} exceeds data length 86565296'
terminating with uncaught exception of type NSException

**Comment by luluaidota** [comment]
应该是数据长度越界了，但是我不太清楚是怎么导致的，本来前面还能分析，后来删除了一下无用类之后，就分析不了了~

**Comment by springwinding** [comment]
已修复越界的问题， 更新一下在试试， 如有问题， 请+微信： zqlong320

**Comment by luluaidota** [comment]
测试后已经可以了
