### ISSUE TITLE
非常好的工具，可以检测静态库无用类吗？

### ISSUE THREAD

**Issue by jacobjiangwei** [wuba/WBBlades#8]
我们工作上很多静态库，交付产物也是SDK。
体积优化上，我们希望可以支持检测静态库？需要我协助写代码更新这部分功能也可以，可以私聊~

**Comment by pilaf-king** [comment]
> 我们工作上很多静态库，交付产物也是SDK。
> 体积优化上，我们希望可以支持检测静态库？需要我协助写代码更新这部分功能也可以，可以私聊~

支持检测静态库的，私聊哈，我QQ395565391
